### ISSUE TITLE
Create and reuse component

### ISSUE THREAD

**Issue by yarsky-tgz** [SouthPalmire/sandbox#14]
At `GeneratorSka.vue` we have two similar parts of code 

```vue
  <button type="button" @click="rows--">-</button>
  {{ rows }}
  <button type="button" @click="rows++">+</button>
```

and 

```vue
  <button type="button" @click="columns--">-</button>
  {{ columns }}
  <button type="button" @click="columns++">+</button>
```

let's reuse this code except copy&pasting (it means - let's write code one time, and then just use it again, if needed)

For this you need to create `EditNumber.vue` component, based on template, described above.

It must take `number` prop and then number changes by +\- buttons clicking - `$emit` the `input` event with new number value. 

And, finally, just replace both 'number editors', mentioned above, with this component usage.

**Comment by yarsky-tgz** [comment]
```vue
   <button type="button" @click="rows--">-</button>
  {{ rows }}
  <button type="button" @click="rows++">+</button>
  x
  <button type="button" @click="columns--">-</button>
  {{ columns }}
  <button type="button" @click="columns++">+</button>
```
must be replaced with

```vue
  <EditNumber :value="rows" @input="rows = $event" />
  x
  <EditNumber :value="columns" @input="columns = $event" />
```
  
```

**Comment by SouthPalmire** [comment]
!
